datasource:
  testdb:
    jdbcUrl: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: new_password
    driverClassName: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: false